### ISSUE TITLE
PayPal auf Startseite CH

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#13]
HG von PayPal, Text als Übersetzung in Digital Publisher !!

**Comment by MWeid** [comment]
Was ist damit? Ist bereits 1,5 Monate offen. Nicht so wichtig?

**Comment by MWeid** [comment]
@ckreuter Sag, weisst was damit gemeint ist?

**Comment by ckreuter** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 12.04.2017 bis 23.04.2017 nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet und kann deshalb erst ab dem 24.04.2017 beantwortet werden. 

Mit freundlichen Grüßen

Christoph Kreuter
