### ISSUE TITLE
"Rücksendung nicht mehr kostenlos" - Abklären!

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#15]
Herr Prof. will, dass wir die kostenlose Rücksendung sofort abdrehen, obwohl er weiß dass es uns nicht mal 5 Euro kostet. Er hat klar und deutlich drauf bestanden, dass die Rücksendung wieder kostenpflichtig ist. 

**Bitte abklären ob und wie umsetzbar,** ich würde ihn aber lieber davon überzeugen dass die kostenlose Retoure sinnvoller ist. Das Argument "kostenpflichtig senkt die Bestellungen" kennt er und interessiert ihn absolut nicht, weil ihm "kostenpflichtig senkt die Retouren" gerade wichtiger ist.

**Comment by MWeid** [comment]
Gibt's hierzu schon Infos? Bzw. konntest du den Prof. schon umstimmen? :-)

**Comment by mottermayr** [comment]
Aktuell sind wir bei "momentan kostenpflichtige Retouren". Werden aber sobald wie möglich wieder umstellen!

**Comment by ckreuter** [comment]
Sehr geehrte Damen und Herren,

ich bin vom 06.02.2017 bis 13.02.2017 nicht erreichbar. Ihre E-Mail wird nicht weitergeleitet und kann deshalb erst ab dem 13.02.2017 beantwortet werden. 

Mit freundlichen Grüßen

Christoph Kreuter
