### ISSUE TITLE
Flora + Matilda + Dottie einbuchen

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#20]
EL 8900 Matilda Bügel BH schwarz (in Continuity)
EL 8905 Matilda Slip schwarz (in Continuity)
EL 4200 Kiki Bügel BH schwarz(in Continuity)
EL 4030 Cate Soft Cup BH mit Bügeln weiß (in AW 15 imagery)

+ Bitte VOR Donnerstag Texte + Bilder einspielen

Bilder sind unter dem Link zu finden:
https://www.dropbox.com/sh/71vfszxp0s5qu9s/AADvv0L3-V6YI1WODs_Fd4tia?dl=0

Am Donnerstag bitte einbuchen!

**Comment by MarjanMileski** [comment]
Ist angelegt mit Texten und Bildern, Lagerstand werden wir morgen einbuchen.

**Comment by MarjanMileski** [comment]
Kiki Bügel BH schwarz und Cate Soft Cup BH fehlt Lagerstand noch

**Comment by MWeid** [comment]
Wie & wer trägt das ein? Die Lagermitarbeiter in Linz? Oder direkt CK wenn er wieder in Linz?

**Comment by MWeid** [comment]
Ok, laut MM wird CK Flora nächste Woche direkt einbuchen - super!

**Comment by ckreuter** [comment]
Wurde eingebucht und kann verkauft werden!
