### ISSUE TITLE
Zugang zu Instagram Profil herstellen

### ISSUE THREAD

**Issue by katerinamiracle** [MiracleWoman/hq#22]
https://www.instagram.com/miracle.woman/

Kann leider nicht mehr hergestellt werden, da weder E-Mail Adresse noch Passwort bekannt. 
Alternative: Um Löschung bitten und neu anlegen

https://help.instagram.com/409847499070242
"Wenn du dein Passwort vergessen und keinen Zugriff mehr auf dein E-Mail-Konto hast, können wir das Instagram-Konto nicht mehr für dich freigeben. Dies ist auch der Fall bei Konten, die mit einer falsch geschriebenen E-Mail-Adresse registriert sind."

**Comment by MWeid** [comment]
Spricht @mottermayr mit dem Prof am Dienstag ab!

**Comment by MWeid** [comment]
@katerinamiracle War ma da eigentlich jetzt erfolgreich?

**Comment by katerinamiracle** [comment]
Noch nicht, habe gestern die zugangsdaten zum pivaten account von Prof. Schmidts Tocher bekommen und versehentlich gelich das pw zurück gestetzt. Habe dann noch seine Frau angeschrieben mit der Frage, ob sie einen hinweis hat. Falls da auch nichts kommt, werden wir einen neuen account anlegen müssen. 
Ich  gebe dir Bescheid.

**Comment by katerinamiracle** [comment]
Zugangsdaten können definitiv nicht aufgetrieben werden. Wir haben nun einen neuen Insta Account siehe ID liste.
