### ISSUE TITLE
Ergänzung der fehlenden deutschsprachigen Texte

### ISSUE THREAD

**Issue by katerinamiracle** [MiracleWoman/hq#23]

**Comment by MWeid** [comment]
Könn(t) ma am Mo im Jour Fixe besprechen!

**Comment by katerinamiracle** [comment]
das haben wir noch nicht besprochen, oder? oder ist das das Thema AGB?

**Comment by MWeid** [comment]
Zum einen "Ja", also der Anwalt muss da noch sein Feedback geben, und das FAQ muss noch erweitert werden. Abschließend -und das ist die zache Hacken- sollten noch alle Produktdetailtexte (also ca. 300 Stück) drübergelesen werden. Das ist aber eine langfristige Sache, die (wahrscheinlich) viel Zeit beanspruchen wird.

**Comment by MWeid** [comment]
Im Grunde überschneiden sich der Task mit diesem Task hier: https://github.com/MiracleWoman/hq/issues/24

**Comment by MWeid** [comment]
Da das eh auch Task #24 betrifft, close ich das mal hier!
