### ISSUE TITLE
Amazon: Angelina offenbar mit unvollständigen Informationen

### ISSUE THREAD

**Issue by MWeid** [MiracleWoman/hq#26]
![angelina](https://cloud.githubusercontent.com/assets/24407071/22058757/6b0be636-dd6a-11e6-8a72-5417aa2a4857.png)

Womöglich ist (auch) das Bild inkorrekt. Es sollte einen weißen HG besitzen!

**Comment by MWeid** [comment]
Hier der direkte Amazon-Link: https://www.amazon.de/dp/product/B01M0G4N50

**Comment by MarjanMileski** [comment]
Wenn ich das Produkt bei Lagerbestand verwalten, bearbeite werden die Änderungen nicht wirksam. Auch nicht wenn ich Bilder neu hochlade. Es bleiben die alte Beschreibung und Bilder drinnen. Mit der Amazon Suchfunktion finde ich auch den gewünschten Artikel nicht.

**Comment by MWeid** [comment]
Shit! @ckreuter Mal wieder ein Amazon-Issue? ;-)

**Comment by MWeid** [comment]
Scheint zu funken.
