### ISSUE TITLE
SEO-Text "Über Miracle Woman"

### ISSUE THREAD

**Issue by MWeid** [MiracleWoman/hq#28]
MO hat nen netten Text geschrieben, den sie whs auf die Frontpage platzieren möchte. Siehe hier: 
![seo text](https://cloud.githubusercontent.com/assets/24407071/22152045/4de65466-df21-11e6-8e72-d88cd4162896.png)

**Comment by MWeid** [comment]
Hab den "Shop für Grosse Cups"-Text noch angepasst, da ja wir ja nix handgenähtes anbieten! ;-) 

> Der Online-Shop Miracle Woman vertreibt unter der Eigenmarke passform-optimierte Dessous und Bademode für große Cup-Größen bis Cup K. Die hochwertig verarbeiteten Wäscheteile zeichnen sich aus durch perfekten Sitz, hohen Tragekomfort und durchdachte Designs in limitierten Stückzahlen. Außerdem vertreibt Miracle Woman Accessoires, sowie Dessous und Bademode weiterer bewährter Labels.

**Comment by MWeid** [comment]
Hier ist das RAW-File von MO
[seotext.zip](https://github.com/MiracleWoman/hq/files/719541/seotext.zip)

**Comment by mottermayr** [comment]
Bitte "handgefertigt" wieder einfügen haha

**Comment by MWeid** [comment]
https://www.plentyone.de/
