### ISSUE TITLE
Kundenumfrage

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#46]
Technische Umsetzung: 

Kunden sollen Code erst erhalten wenn zu NL angemeldet!

Dann aussenden + Reminder nach 7 tagen

**Comment by mottermayr** [comment]
Erste Codes ausgeschickt, siehe Tabelle "Umfrage Teilnehmer"  \\DISKSTATION2\Miracle-Woman\Marketing\Newsletter

**Comment by MWeid** [comment]
Nächste Woche wird das Thema geclosed bzw. die Daten ausgewertet!
