### ISSUE TITLE
Landingpage Valentinstag + NL

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#47]
Lager Bescheid geben: 

15 Strumpfbänder zu Bestellung beilegen bei Bestellung über 90,- EUR (Kathi darf Farbe wählen passend zu Bestellung)

Gutschein in Paket beilegen - Evtl. Brief mit Gutschein ausdrucken & beilegen??

**Comment by ckreuter** [comment]
NL raus und Landingpage fertig ;)
