### ISSUE TITLE
Videoproduktionen

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#53]
+ Fehlende Angaben an Agenturen schicken damit sie Angebote machen können: 
 Clipvilla, Mediakraft + Warda

+ Konzepte ausarbeiten, Inhalte vorgeben, Models engagieren, Termine definieren, …

**Input von Hrn. Prof Schmidt:** 
MW würde gutem „Preis/Leistungs-Verhältnis“
Alle 10 Tage einen neuen kurzen Videoclip in den shop stellen UND auf you tube, facebook usw. verbreiten.
Models werden von MW gestellt, tunlichst auch daraus eine Moderatorin (siehe „unsere“ Moderatorin im Kurz-Film minou-TV)
--einige unserer models haben auch  im grossen Street-Video GUT GESPROCHEN!!
Kampagnen-Zeitraum: Fortlaufend, so lange gute Ideen erfolgreich sind.
Produktions-Ort:
Zentrallager LINZ/dort kann auch kleines Studio eingerichtet werden.
Produktion auch in Studio des Produzenten möglich.
Zum TEST  bitte EIN Video anfragen:
„Fitting big Bras/Bikinis“  und/oder
„Wie stelle ich meine BH/Bikini-Grösse fest“
Begleitende social media-postings—können wir selbst machen, oder?

**Comment by MWeid** [comment]
Done! Seit letzter Woche - 11.4.
