### ISSUE TITLE
Influencer / Blogger

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#58]
+ Liste auf Google Docs von KC + RR
+ Es wurde noch kein Blogger/Influencer kontaktiert
+ Es gibt keine Vorgabe wie die Zusammenarbeit aussehen muss / keine Budgetvorgabe

+ Kaelyn Schmitt hat MO kontaktiert mit Angebot zu Kooperation, jedoch keine Antwort erhalten

**Comment by MWeid** [comment]
Was ist mit der Kaelyn Schmitt? Irgendein Update?

**Comment by mottermayr** [comment]
Fr. Schmitt hat offenbar kein Interesse an einer Zusammenarbeit.

Auf der Bloggerliste sind jedoch mMn ohnehin einige vielversprechendere Personen (Y)
