### ISSUE TITLE
Shooting Wien

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#61]
+ 03.03.2017
+ Monika Frauenhofer + Britta Tess Visa (KV noch nicht bestätigt)
+ Studio: 1210 Wien, noch nicht reserviert
+ Models wissen Bescheid,  unterschriebene Verträge sind noch nicht retour
+ Produkte noch nicht im Haus/bestellt

**Comment by MWeid** [comment]
Done! Warten nur noch auf bearbeitete Fotos von US-Kathy.
