### ISSUE TITLE
Bannerwerbung auf Zeitungs-Webseiten

### ISSUE THREAD

**Issue by mottermayr** [MiracleWoman/hq#62]
+ Preisliste von GW angefordert (hat noch eine von damals)
+ Grafiken bei Amédé in Arbeit  (1x Set allg. Bademode, 1x Set allg. BHs)

**Comment by MWeid** [comment]
Wennst Fragen hast, dann gib bescheid. Das habe ich 3 Jahre lang intensiv für verschiedene Kunden gemacht.

**Comment by mottermayr** [comment]
Prof. meinte wir probieren mal ca 2.000,- Euro - weil Gerlinde meinte es ist sinnlos. Außerdem hat das wohl damals eine Agentur erledigt, ich warte noch auch die Daten von Gerlinde. 

Und ja, Hilfe wäre super denn ich habe davon absolut keine Ahnung xD

**Comment by MWeid** [comment]
Haha, auf 2.000 Euro wird sich whs keine Tageszeitung einlassen. Vor allem dann nicht, wenn ne Agentur dahinter steht, welche ja auch ca. 15% vom Kuchen abbekommt. ;-)

**Comment by mottermayr** [comment]
Und nur Woman oder Brigitte oder sowas? Vll können wir dort nen Deal machen - damit zumindest irgendwas in diese Richtung gemacht wird - er möchte es unbedingt obwohl wir ihm beide ausdrücklich gesagt haben dass es nicht so der Burner werden wird :/

**Comment by MWeid** [comment]
Tarife kannst du dir eh mal ansehen! ;-)
https://www.vgn.at/a/woman-tarife
http://www.gujmedia.de/online/portfolio/brigittede/preise-2017/

**Comment by MWeid** [comment]
Was ich damit sagen will: Wenn du dir die Preise z.B. auf Brigitte ansiehst, dann ist ein Mindestvolumen von 4.500 Euro angegeben! ;-)
