### ISSUE TITLE
Einrichtung der zweisprachigen Signaturen bei allen MAs, insbesondere bei Claudia 

### ISSUE THREAD

**Issue by katerinamiracle** [MiracleWoman/hq#87]

**Comment by MWeid** [comment]
![signatur](https://cloud.githubusercontent.com/assets/24407071/23898061/e3f9b1e8-08af-11e7-87be-3c9c3f950366.png)
Im Grunde sollte das reichen. Also als einmalige Änderung für DE/AT, oder?

**Comment by MWeid** [comment]
Für Claudia müssten wir ja ohnehin einen zweiten englischsprachigen Account anlegen
