### ISSUE TITLE
Shopanalyse

### ISSUE THREAD

**Issue by katerinamiracle** [MiracleWoman/hq#90]
Lieber Christoph, lieber Michael, 

ich bitte euch kurz zusammenzufassen, welche Maßnahmen zur Qualitätssicherung des Onlineshops laufend von euch durchgeführt werden und 
lieber Christoph, dich bitte ich, bei der Firma deines Vertrauens eine Analyse durchführen zu lassen. 

Ziel: Ich möchte Prof. Schmidt darüber informieren, dass Qualitätssicherung ohnehin ein Teil eurer Arbeit ist und dennoch seinem Wunsch nach externer Analyse nachkommen. 

Lgk

**Comment by katerinamiracle** [comment]
Guetezeichen.at wurde am 06.03.2017 von @MWeid mit Analyste beauftragt

**Comment by katerinamiracle** [comment]
Angebot: https://secure.everbill.eu/mails/document_download/14906e2a0b984ca3827fc080d7e4f044

**Comment by MWeid** [comment]
@katerinamiracle Gibt's hierzu bereits was neues?
