### ISSUE TITLE
Launch - Produkttexte DE 

### ISSUE THREAD

**Issue by katerinamiracle** [MiracleWoman/hq#93]
- Freya / AA2034 Still-BH - MODELL Dotty schwarz/weiß
- Nicol Djumon / 14119 gemoldeter BH - MODELL Delia dunkelblau
- Nicol Djumon / 14127 Brazil Tanga - MODELL Delia dunkelblau
- Charmline / 1713 Badeanzug - MODELL Metallic Rays schwarz - metallic
- Charmline / 1712 Badeanzug - MODELL Dynamic Beach - multicolour
- Charmline / 2051 Bikini Set 124 - MODELL Dynamic Beach - multicolour
- L'Idea / 7581 Bikini-Set (Top und Bottom) mit Schalen - MODELL Bora Bora
- L'Idea / 7271 Bikini Top - MODELL Bahamas (grün/türkis colorblocking)
- L'Idea / 403 Bikinihose - MODELL Bahamas (grün/türkis colorblocking)
- Fantasie / Badeanzug - MODELL Lanai (weiß/blau)
- Fantasie / Bikini Top - MODELL Lanai (weiß/blau)
- Fantasie / Bikini Pant - MODELL Lanai (weiß/blau)

**Comment by katerinamiracle** [comment]
Hi, ich mache die unteren 6 und du die oberen, ok lieber Marjan?

**Comment by MarjanMileski** [comment]
Ok passt machen wir das so :)
