### ISSUE TITLE
EN Übersetzung von Info zu Widerrufsrecht 

### ISSUE THREAD

**Issue by katerinamiracle** [MiracleWoman/hq#95]
Informationen zur Ausübung des Widerrufsrechts
Als Verbraucher können Sie das gesetzlich gewährte Rücktritts- bzw. Widerrufsrecht ausüben (siehe Punkt
2). Wir nehmen unabhängig davon bei uns gekaufte Waren freiwillig unter den unten angeführten
Voraussetzungen zurück:
1. Freiwillige Rücknahme von Waren = Retoure
Eine hohe Kundenzufriedenheit ist unser Ziel! Daher können Sie bei uns gekaufte Artikel, unabhängig von Ihrem
Rücktritts- bzw. Widerrufsrecht als Verbraucher, innerhalb von 14 Tagen kostenfrei an uns retournieren, falls
Ihnen die Ware nicht zusagt.
Nutzen Sie dazu das Retourenportal auf unserer Webseite: nach Eingabe der erforderlichen Informationen
können Sie Ihren Retouren-Begleitschein und die Paketmarke für Ihre kostenfreie Postaufgabe ausdrucken.
Wählen Sie einen anderen Versender als auf der Paketmarke vorgedruckt, tragen Sie die Rücksendekosten
selbst.
Nach erfolgter Prüfung erhalten Sie den gezahlten Kaufpreis und bei vollständiger Retoure außerdem die
Versandkosten umgehend rückerstattet. Werden Artikel unvollständig retourniert, kann leider keine Erstattung
erfolgen. Bitte haben Sie auch Verständnis dafür, dass wir benutzte, verschmutzte oder beschädigte Ware nicht
zurücknehmen können. Bitte entfernen Sie auch das Etikett nicht, da wir auch solche Artikel nicht annehmen.
2. Widerrufsrecht
Sie haben das Recht, Ihre Vertragserklärung oder einen bereits zustande gekommenen Vertrag binnen 14
Tagen ohne Angabe von Gründen zu widerrufen. Die Widerrufsfrist beträgt 14 Tage ab dem Tag, an dem Sie
oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Waren in Besitz genommen haben bzw.
hat. Falls Sie die Waren im Rahmen einer einheitlichen Bestellung bestellt haben und diese Waren getrennt
geliefert werden, beginnt die Widerrufsfrist an dem Tag, an dem Sie oder ein von Ihnen benannter Dritter, der
nicht der Beförderer ist, die letzte Ware in Besitz genommen haben bzw. hat.
Um Ihr Widerrufsrecht auszuüben, müssen Sie uns (Anexus GmbH, Neubaugasse 68/1/6, 1070 Wien,
Österreich, kundendienst@miracle-woman.com) mittels einer eindeutigen Erklärung (Brief oder E-Mail) über
Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das hier abrufbare Muster-
Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist. Zur Wahrung der Widerrufsfrist reicht es
aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.
3. Folgen des Widerrufs
Wenn Sie Ihre Vertragserklärung oder einen bereits zustande gekommenen Vertrag widerrufen, haben wir Ihnen
alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Versandkosten (mit Ausnahme der
zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns
angebotene, günstigste Standardlieferung gewählt haben – die vom Versender verrechnete Nachnahmegebühr
wird von uns keinesfalls erstattet), unverzüglich und spätestens binnen 14 Tagen ab dem Tag zurückzuzahlen,
an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist.
Für die Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion
eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden
Ihnen wegen dieser Rückzahlung Entgelte berechnet. Wir können die Rückzahlung verweigern, bis wir die
Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren
zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist.
Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen 14 Tagen ab dem Tag, an dem Sie uns
über den Widerruf dieses Vertrags unterrichten, zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn
Sie die Waren vor Ablauf der Frist von 14 Tagen absenden. Die Kosten der Rücksendung sind vom Kunden
selbst zu tragen.
Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur
Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit
ihnen zurückzuführen ist.
Die Rücksendung der Ware ist zu richten an:
Miracle Woman
Ignaz-Maier-Straße 7
4020 Linz
Österreich
Bewahren Sie Ihre Versandbestätigung bitte sorgfältig auf! Diese dient als Nachweis für die Rücksendung,
falls das Paket auf dem Weg zu uns verloren geht.
HINWEIS: Der Postweg, bis Ihre Retoure in unserem Lager eintrifft, kann bis zu 10 Werktagen dauern. Sobald
wir die Retoure erhalten, senden wir Ihnen eine Bestätigung per E-Mail und veranlassen die Rückerstattung!
Sie haben kein Widerrufsrecht bei Verträgen über
 Waren, die nach Kundenspezifikationen angefertigt werden oder eindeutig auf persönliche Bedürfnisse
zugeschnitten sind.
 Waren, die versiegelt geliefert werden und aus Gründen des Gesundheitsschutzes oder aus
Hygienegründen nicht zur Rückgabe geeignet sind, sofern deren Versiegelung nach der Lieferung entfernt
wurde.

**Comment by MWeid** [comment]
Ist das bereits fertig?

**Comment by katerinamiracle** [comment]
Hi, wenn der Text oben Teil der AGBs oder FAQs ist, dann ist er fertig. Dazu hier auch das Formular auf EN. https://docs.google.com/document/d/1nAtI-9lLYBvGrCumbEqKJ2qJ1tO4TFoLfeMv9k_wcFM/edit?usp=sharing
