### ISSUE TITLE
Fehlende Produtktdarstellung bei Bikini-Cups

### ISSUE THREAD

**Issue by MWeid** [MiracleWoman/hq#96]
![nix da oida](https://cloud.githubusercontent.com/assets/24407071/23997147/785f29de-0a50-11e7-9a43-32e85d7c133e.png)
Wenn man als BH-Oberteil nur Cup E oder F auswählt, dann kommt gar nix.

**Comment by MWeid** [comment]
@Mich - dann entsprechend in Adwords wieder anpassen.

**Comment by ckreuter** [comment]
Funktioniert wieder 💃
